// <auto-generated />
namespace Vic.SportsStore.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ProductRev5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductRev5));
        
        string IMigrationMetadata.Id
        {
            get { return "202008230546312_ProductRev5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
